const data = {
  products: [
    {
      name: "Hand bag",
      slug: "handbag",
      category: "handbag",
      image: "/images/handbag3.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: "Lavie",
      rating: 4.5,
      numReviews: 10,
      description: "high quality handbag",
    },
    {
      name: "Duffle bag",
      slug: "Duffle bag",
      category: "dufflebag",
      image: "/images/dufflebag.jpg",
      price: 250,
      countInStock: 0,
      brand: "Roshan",
      rating: 4.0,
      numReviews: 10,
      description: "high quality dufflebag",
    },
    {
      name: "Back bag",
      slug: "Back bag",
      category: "backbag",
      image: "/images/backbag.jpg",
      price: 25,
      countInStock: 15,
      brand: "Skybags",
      rating: 4.5,
      numReviews: 14,
      description: "high quality backbag",
    },
    {
      name: "Trekking bag",
      slug: "Trekking bag",
      category: "trekkingbag",
      image: "/images/trekkingbag.jpg",
      price: 65,
      countInStock: 5,
      brand: "Wildcraft",
      rating: 4.5,
      numReviews: 10,
      description: "high quality trekkingbag",
    },
  ],
};
export default data;
